# Generated by Django 4.0.1 on 2022-01-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Почта',
                'verbose_name_plural': 'Почты',
                'db_table': 'email',
            },
        ),
        migrations.DeleteModel(
            name='UserEmail',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.ManyToManyField(default=None, null=True, related_name='email_users', to='drf_api.Email', verbose_name='Почта'),
        ),
    ]
