# Generated by Django 3.2.7 on 2022-02-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='personal_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Идентификационный номер клиента'),
        ),
        migrations.AlterField(
            model_name='department',
            name='personal_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Идентификационный номер департамента'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='personal_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Идентификационный номер Юр. лица'),
        ),
    ]
