# Generated by Django 3.2.7 on 2022-01-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0002_email_delete_useremail_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=True, verbose_name='is_admin'),
        ),
    ]
