# Generated by Django 3.2.7 on 2022-02-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0003_auto_20220207_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='parent_department',
            new_name='parent',
        ),
    ]
