# Generated by Django 3.2.7 on 2022-01-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0003_customuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='sender',
            new_name='user',
        ),
    ]
