# Generated by Django 3.2.7 on 2022-02-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0004_rename_parent_department_department_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='level',
        ),
        migrations.RemoveField(
            model_name='department',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='department',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_dep', to='drf_api.department', verbose_name='Родительский департамент'),
        ),
    ]
