# Generated by Django 3.2.7 on 2022-01-29 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0004_rename_sender_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='personal_id',
            field=models.PositiveIntegerField(default=101, unique=True, verbose_name='Идентификационный номер клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+7\\d{10}$')], verbose_name='Номер телефона пациента'),
        ),
        migrations.AlterField(
            model_name='department',
            name='personal_id',
            field=models.PositiveIntegerField(default=103, unique=True, verbose_name='Идентификационный номер департамента'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='personal_id',
            field=models.PositiveIntegerField(default=102, unique=True, verbose_name='Идентификационный номер Юр. лица'),
        ),
    ]
