# Generated by Django 3.2.7 on 2022-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0005_auto_20220129_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='personal_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Идентификационный номер департамента'),
        ),
    ]
