# Generated by Django 3.2.7 on 2022-01-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0006_alter_department_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworks',
            name='count_extend',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во использований пользователем'),
        ),
        migrations.AddField(
            model_name='socialnetworks',
            name='name',
            field=models.CharField(choices=[('VK', 'VK'), ('FB', 'Facebook'), ('ОК', 'Оk'), ('INST', 'Instagram'), ('TEG', 'Telegram'), ('WA', 'WhatsApp'), ('VB', 'Viber')], default='', max_length=24, unique=1, verbose_name='Социальная сеть'),
        ),
        migrations.AlterField(
            model_name='department',
            name='personal_id',
            field=models.PositiveIntegerField(blank=True, unique=True, verbose_name='Идентификационный номер департамента'),
        ),
        migrations.CreateModel(
            name='SocialNetworksRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=999, verbose_name='Адрес сети')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_api.client', verbose_name='департамент')),
                ('social_networks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_api.socialnetworks', verbose_name='Юр. лицо')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='social_network',
            field=models.ManyToManyField(through='drf_api.SocialNetworksRef', to='drf_api.SocialNetworks', verbose_name='департаменты'),
        ),
    ]
