# Generated by Django 3.2.7 on 2022-01-29 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0008_auto_20220129_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentRef',
            new_name='DepartmentLegalEntityRef',
        ),
        migrations.AlterField(
            model_name='client',
            name='social_network',
            field=models.ManyToManyField(through='drf_api.SocialNetworksRef', to='drf_api.SocialNetworks', verbose_name='Социальные сети'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='DepartmentClientRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_api.client', verbose_name='Физ лицо')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_api.department', verbose_name='департамент')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='departments',
            field=models.ManyToManyField(through='drf_api.DepartmentClientRef', to='drf_api.Department', verbose_name='департаменты'),
        ),
    ]
