# Generated by Django 3.2.7 on 2022-01-29 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0009_auto_20220129_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentclientref',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создании'),
            preserve_default=False,
        ),
    ]
