# Generated by Django 3.2.7 on 2022-01-29 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0010_departmentclientref_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentclientref',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения'),
        ),
        migrations.AlterField(
            model_name='departmentclientref',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_api.department', verbose_name='департамент'),
        ),
        migrations.AlterField(
            model_name='departmentlegalentityref',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_api.department', verbose_name='департамент'),
        ),
    ]
