# Generated by Django 3.2.7 on 2022-01-29 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0013_auto_20220129_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentclientref',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_api.client', verbose_name='Физ лицо'),
        ),
        migrations.AlterField(
            model_name='departmentlegalentityref',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_api.legalentity', verbose_name='Юр. лицо'),
        ),
    ]
