# Generated by Django 3.2.7 on 2022-01-30 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0015_auto_20220129_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.ManyToManyField(default=None, related_name='email_users', to='drf_api.Email', verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='departmentlegalentityref',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_api.department', verbose_name='департамент'),
        ),
        migrations.AlterField(
            model_name='departmentlegalentityref',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_departament', to='drf_api.legalentity', verbose_name='Юр. лицо'),
        ),
    ]
